### ISSUE TITLE
Spec not passed on long integer

### ISSUE THREAD

**Issue by andraantariksa** [crystal-community/toml.cr#21]
When I run `crystal spec`, it will give me a 2 test error, which caused by StackOverFlow. Actually, the JSON implementation also have a StackOverFlow when it try to parse `-9223372036854775808`. So, I think the test it's pretty trivial and I change it into `-9223372036854775807` which works fine

```
require "json"

puts Int64.from_json("-9223372036854775808")
```

https://play.crystal-lang.org/#/r/80z2

Can I make a pull request to change the test?

**Comment by veelenga** [comment]
Thanks. Could you please do that as a part of #22 ?
